### ISSUE TITLE
install_requires should fix dependencies to specific versions

### ISSUE THREAD

**Issue by svisser** [eriktaubeneck/ordbok#3]
The `install_requires` value in `setup.py` does not specify the exact versions (`dependency==0.1.0`) and / or version bounds (`dependency<=0.2`). This means that someone could install this project a year from now and it may not work because a dependency could have introduced a backwards incompatible change. It's therefore better to specify the versions and upgrade them yourself when you've verified that a newer version of a dependency works fine with this project.

**Comment by woutervh** [comment]
You should not assume that a major update of a dependency will certainly break your application.

specifying minimum version is great, 
but maximum versions easily leads to dependency-hell.

Only specify them if:
1) you know for certain your app will break
2) you are now to going fix that
